---

default:
  tags:
    - dev
    - developers

variables:
  DOCKER_IMAGE: "code.usgs.gov:5001/devops/images/usgs/docker:20"
   


# Do not run for merge requests
workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

stages:
  - end-to-end



.docker_login:
  before_script:
    - |
      test -n "${CI_REGISTRY_USER}" -a -n "${CI_REGISTRY_PASSWORD}" \
          && echo "${CI_REGISTRY_PASSWORD}" | \
          docker login \
          --username "${CI_REGISTRY_USER}" \
          --password-stdin \
          "${CI_REGISTRY}";
  cache:
    paths:
      - .trivy/
  services:
    - alias: docker
      name: "${DOCKER_IMAGE}-dind"

End To End Test:
  extends:
    - .docker_login
  image: "${DOCKER_IMAGE}" 
  script:
    - LOCAL_IMAGE="wasp"
    - docker build --build-arg CI_REGISTRY="True" -t "${LOCAL_IMAGE}" .
    - docker run wasp
  stage: end-to-end
  variables:
    DOCKER_DRIVER: overlay2
