---

default:
  tags:
    - chs-shared
    - dind

variables:
  REPOSITORY: "ghsc/neic/algorithms/neic-finitefault"
  DOCKER_IMAGE: "code.usgs.gov:5001/devops/images/usgs/docker:20"
  WASP_IMAGE: "${CI_REGISTRY}/${REPOSITORY}/wasp-ubuntu-dependencies:latest"
   


# Do not run for merge requests
workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

stages:
  - init
  - test
  - deploy


##
# Define type of pipeline (on a fork or on the upstream project)
##
.fork: &fork
  if: $CI_PROJECT_PATH != 'ghsc/neic/algorithms/neic-finitefault'

.upstream: &upstream
  if: >
    $CI_PROJECT_PATH == 'ghsc/neic/algorithms/neic-finitefault'
    && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


.docker_login:
  before_script:
    - |
      test -n "${CI_REGISTRY_USER}" -a -n "${CI_REGISTRY_PASSWORD}" \
          && echo "${CI_REGISTRY_PASSWORD}" | \
          docker login \
          --username "${CI_REGISTRY_USER}" \
          --password-stdin \
          "${CI_REGISTRY}";
  cache:
    paths:
      - .trivy/
  services:
    - alias: docker
      name: "${DOCKER_IMAGE}-dind"

## -------------------------------------
#  Init Stage
## -------------------------------------
Poetry:
  artifacts:
    paths:
      - poetry.toml
      - .venv
      - dist/lambda
    expire_in: 1 week
  image: "${WASP_IMAGE}"
  script:
    - poetry config virtualenvs.in-project true --local
    - poetry install
    - poetry run poe okada
    - poetry run safety check
  stage: init

Fortran:
  artifacts:
    paths:
      - fortran_code
    expire_in: 1 week
  image: "${WASP_IMAGE}"
  script:
    - source ./environment.d/ubuntu.sh
    - cp -r "/home/usgs-user/finitefault/tectonicplates" ./fortran_code/
    - cp "/home/usgs-user/finitefault/fortran_code/gfs_nm/long/fd_bank" ./fortran_code/gfs_nm/long/fd_bank
    - cp "/home/usgs-user/finitefault/fortran_code/info/LITHO1.0.nc" ./fortran_code/info/LITHO1.0.nc
    - bash install.d/wasp.sh "$(pwd)"
  stage: init

## -------------------------------------
#  Test Stage
## -------------------------------------

Python Lint:
  image: "${WASP_IMAGE}"
  script:
    - poetry run poe lint
  stage: test

Python Test:
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: junit.xml
  image: "${WASP_IMAGE}"
  script:
    - source ./environment.d/ubuntu.sh && poetry run poe test
  stage: test

Shell Check:
  image: usgs/ubuntu:latest
  script:
    - apt install -y shellcheck
    - shellcheck install.sh -x
    - shellcheck install.d/*
    - shellcheck environment.d/*
  stage: test

## -------------------------------------
#  Deploy Stage
## -------------------------------------

Docker Deploy:
  dependencies:
    - "Python Test"
    - "Shell Check"
  extends:
    - .docker_login
  image: "${DOCKER_IMAGE}"
  rules:
    - if: "$SCHEDULED"
    - changes:
          - Dockerfile
          - fortran_code/*
          - install.d/*
          - poetry.lock
          - pyproject.toml
          - src/*   
  script:
    -  |
      ARGS=();
      for ARG in ${BUILD_ARGS}; do
        ARGS+=("--build-arg" "${ARG}=${!ARG}");
      done
    - LOCAL_IMAGE="${CI_REGISTRY}/${REPOSITORY}/${IMAGE}:${TAG}"
    - echo "${ARGS[@]} --tag ${LOCAL_IMAGE}" 
    - docker build "${ARGS[@]}" --tag "wasp-latest" .
    - TAG="${CI_COMMIT_TAG:-latest}"
    - DEPENDENCY_IMAGE="${CI_REGISTRY}/${REPOSITORY}/"wasp-ubuntu-dependencies":${TAG}"
    - docker build "${ARGS[@]}" --target dependencies -t "${DEPENDENCY_IMAGE}" .
    - FF_IMAGE="${CI_REGISTRY}/${REPOSITORY}/"wasp-ubuntu":${TAG}"
    - docker build "${ARGS[@]}" --target finitefault -t "${FF_IMAGE}" .
    # remove dependencies that are no longer needed on the runner
    - rm -rf ./*
    # push to registry
    - if [ "${CI_PROJECT_PATH}" != "ghsc/neic/algorithms/neic-finitefault" ]; then
      echo "Skipping push on non-upstream (${CI_PROJECT_PATH})";
      exit 0;
      fi
    # push dependencies image
    - echo "Pushing image ${DEPENDENCY_IMAGE}"
    - docker push "${DEPENDENCY_IMAGE}";
    # push finitefault image
    - echo "Pushing image ${FF_IMAGE}"
    - docker push "${FF_IMAGE}";
  stage: deploy
  variables:
    BUILD_ARGS: DCW_VERSION GMT_VERSION GSHHG_VERSION 
    DCW_VERSION: "2.1.1"
    DOCKER_DRIVER: overlay2
    GMT_VERSION: "6.4.0"
    GSHHG_VERSION: "2.3.7"
    PYTHON_VERSION: "3.10"
