name: ff-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.2
  - black=24.4.2
  - cartopy=0.23.0 
  - geos=3.12.2
  - idna=3.7
  - isort=5.13.2
  - matplotlib=3.9.1
  - mypy=1.10.0
  - netcdf4=1.7.1
  - notebook=7.2.1
  - numpy=1.26.4
  - obspy=1.4.1
  - pygmt=0.12.0
  - pyproj=3.6.1
  - pytest=7.4.4
  - pytest-cov=4.1.0
  - safety=2.3.4
  - scipy=1.14.0
  - shapely=2.0.5
  - sqlalchemy=1.4.53
  - typer=0.9.4
  - pip:
    - pyrocko==2023.10.11
    - poethepoet==0.20.0
    - okada_wrapper==18.12.07.3

